Lang.prototype.pack.en = {
	"token": {
		"Ingreso":"Ingress",
		"Datos incorrectos":"Data incorrect",
		"Usuario":"User",
		"Contraseña":"Password",
		"Ingresar":"Sign in",
		"Super Administrador":"Super Administrator",
		"Inicio":"Home",
		"Editar Datos":"Edit Data",
		"Cambiar Contraseña":"Change Password",
		"Salir":"Logout",
		"Bienvenido al Sistema de Gestion de Contenidos":"Welcome to Content Management System",
		"Idioma":"Language",
		"Listado de Imagenes":"List of pictures",
		"Diapositiva":"Slideshow",
		"Contenido":"Content",
		"Listar imagenes":"List images",
		"Agregar imagen":"Add picture",
		"Contenido inicio":"Home Content",
		"Formulario":"Form",
		"Compañía de Seguros":"Insurance Company",
		"Desgravamen":"Disencumbrance",
		"Administración Datos Desgravamen":"Disencumbrance Data Management",
		"Administración Pólizas":"Management Renters",
		"Administración Ocupación":"Management Occupation",
		"Certificado Médico":"Medical Certificate",
		"Administración Correos":"Mail management",
		"Agencias":"Agencies",
		"Sucursales":"Locations",
		"Entidades Financieras":"Financial Institutions",
		"Compañías agregadas a Entidades":"Companies added to Entities",
		"Cabecera":"Head",
		"Automotores":"Automotive",
		"Contenido Nosotros":"We contents",
		"Forma de Pago":"Method of payment",
		"Estados":"United",
		"Todo Riesgo Domiciliario":"All Domiciliary Risk",
		"Ramos Técnicos":"Technical Lines",
		"Tipo de Cambio Moneda":"Currency Exchange Rates",
		"Tarjetahabiente":"Cardmember",
		"Modalidad":"Modality",
		"Entidad Financiera":"Financial Institution",
		"Archivo":"File",
		"Texto":"Text",
		"Guardar":"Save",
		"El tamaño máximo del archivo es de 5Mb. Se recomienda que la imagen tenga un ancho de 1000px por un alto de 400px., el formato del archivo a subir debe ser [jpg].":"The maximum file size is 5Mb. It is recommended that the image is 1000px wide by 400px high., The format of the file to upload should be [jpg].",
		"seleccione opcion":"select option",
		"seleccione...":"select...",
		"Listar contenido":"List content",
		"Nosotros":"Us",
		"Preguntas Frecuentes":"Frequent Questions",
		"Actualizar imagen":"Image update",
		"Archivo actual:":"Current file:",
		"Lista Contenido Inicio":"Contents List Home",
		"Imagen":"Image",
		"Contenido":"Content",
		"Agregar Contenido":"Add Content",
		"El tamaño máximo del archivo es de 1Mb. Se recomienda que la imagen tenga un alto de 200px y un ancho de 330px., el formato del archivo a subir debe ser [jpg].":"The maximum file size is 1MB. It is recommended that the image is 200px high and 330px wide., The format of the file to upload should be [jpg].",
		"ingrese un texto":"enter text",
		"Volver":"return",
		"Actualizar contenido":"Update Content",
		"No existe el archivo físico":"There is no physical file",
		"Contenido Nosotros":"We contents",
		"no existe el nombre del archivo en la base de datos":"there is no file name in the database",
		"No existe registros alguno, ingrese nuevos registros":"There is no records, enter new records",
		"Editar contenido nosotros":"Edit Content us",
		"campo vacio":"field empty",
		"Error en la consulta":"Error in query",
		"El tamaño máximo del archivo es de 1Mb. Se recomienda que la imagen tenga un ancho de 350px., el formato del archivo a subir debe ser [jpg].":"The maximum file size is 1MB. It is recommended that the image has a width of 350px., The format of the file to upload should be [jpg].",
		"Lista Contenido Preguntas Frecuentes":"Contents List Frequently Asked Questions",
		"Preguntas Frecuentes":"Frequently Asked Questions",
		"Producto":"Product",
		"Lista Compañía de Seguros":"List of Insurance Company",
		"Compañías de Seguros":"Insurance Companies",
		"Estado":"State",
		"habilitado":"enable",
		"deshabilitado":"disabled",
		"Nueva Compañía de Seguros":"New Insurance Company",
		"Titulo Compañía de Seguros":"Title Insurance Company",
		"El tamaño máximo del archivo es de 500Kb. Se recomienda que la imagen tenga un ancho de 140px y un alto de 50px, el formato del archivo a subir debe ser [JPG]":"The maximum file size is 500Kb. It is recommended that the image has a width of 140px and a height of 50px, the file format should be up [JPG]",
		"Cancelar":"Cancel",
		"Ingrese titulo del la Compañia de Seguros":"Enter the title of the Insurance Company",
		"Editar Compañía de Seguros":"Edit Insurance Company",
		"Editar Pólizas":"Edit Renters",
		"Titulo Compañía":"Title Company",
		"No existe ningún registro, razones alguna:":"No registration, some reasons:",
		"Verifique que la Compañía de Seguros este activada":"Verify that the insurance company is activated",
		"Verifique que la Compañía asignada a la Entidad Financiera este activada":"Verify that the Company assigned to the Financial Institution is activated",
		"No existe ningún registro o la Entidad Financiera no esta activada":"No registration or the Financial Institution is not activated",
		"activo":"active",
		"inactivo":"inactive",
		"Listado de Pólizas":"List of Policies",
		"No Póliza":"No Policy",
		"Fecha Inicial":"Initial Date",
		"Fecha Final":"End Date",
		"Agregar Nueva Póliza":"Add New Policy",
		"ingrese el numero de poliza":"enter the policy number",
		"Entidades Financieras":"Financial Institutions",
		"Listar Entidades":"Entities List",
		"Codigo":"code",
		"Nueva Entidad Financiera":"New Financial Institution",
		"Nombre del dominio":"Domain Name",
		"Productos":"Products",
		"El tamaño máximo del archivo es de 2Mb. Se recomienda que la imagen tenga un alto de 75px, el formato del archivo a subir debe ser [JPG] ó [PNG]":"The maximum file size is 2MB. It is recommended that the image has a height of 75px, the file format should be up [JPG] or [PNG]",
		"ingrese titulo":"enter title",
		"ingrese codigo":"enter code",
		"ingrese el nombre del dominio":"enter a domain name",
		"seleccione al menos un producto":"select at least one product",
		"Editar Entidad Financiera":"Edit Financial Institution",
		"no existe el archivo":"file does not exist",
		"Agregar Compañía a Entidades Financieras":"Add Company to financial institutions",
		"Listar Compañía agregadas a Entidades":"Company List Aggregate Entities",
		"Compañía de Seguros":"Insurance Company",
		"Añadir Compañía de Seguros a Entidad Financiera":"Add Insurance Company Financial Institution",
		"Compañia de Seguros":"Insurance Company",
		"seleccione entidad financiera":"select financial institution",
		"seleccione compañia":"select company",
		"Usuarios":"Users",
		"esta compañía ya esta añadida seleccione otra compañía":"this company already added select another company",
		"Listar usuarios":"List users",
		"La(s) entidad(es) financiera(s) no esta activada(s)":"The institution financial not enabled",
		"Tipo usuario":"User Type",
		"Nombre":"Name",
		"Correo electronico":"e-mail",
		"Departamento":"Department",
		"Regional":"Regional",
		"Agencia":"Agency",
		"No existe ningun registro, ingrese nuevos registros":"There is no record, enter new records",
		"Nuevo Usuario":"New User",
		"Confirmar contraseña":"Confirm password",
		"Nombre completo":"Full name",
		"Telefono de la agencia":"Phone number of the agency",
		"No use mayúsculas ni espacios en blanco.":"Do not use capital letters or spaces.",
		"Seleccione los elementos que el usuario podrá editar":"Select the items that you can edit",
		"Ninguno":"None",
		"Formularios":"Forms",
		"Crear Usuarios":"Create Users",
		"Administrar Pólizas":"Managing Policies",
		"Administrar Correos electronicos":"Managing Electronic Mail",
		"Administrar Regional":"Managing Regional",
		"Administrar Agencias":"Administering Agencies",
		"Administrar Tipo de Cambio":"Managing Exchange Rates",
		"seleccione tipo de usuario":"Select user type",
		"seleccione departamento":"select department",
		"ingrese el usuario":"enter the user",
		"ingrese correo electronico":"enter email",
		"Producto Desgravamen":"Product Disencumbrance",
		"Producto Todo Riesgo Domiciliario":"Household Product All Risk",
		"Producto Todo Riesgo Equipo Movil":"All Risk Mobile Product Team",
		"Producto Tarjetahabiente":"Product Cardholder",
		"Producto Automotores":"Automotive Product",
		"Debe de seleccionar al menos un elemento":"You must select at least one item",
		"Editar Usuario":"Edit User",
		"seleccione al menos una entidad financiera":"select at least one financial institution",
		"Contraseña actual":"Current Password",
		"Nueva contraseña":"New Password",
		"Máx. 15 caracteres Mín. 8 caracteres":"Max. Min 8 characters to 15 characters",
		"ingrese la contraseña actual":"enter the current password",
		"Resetear Contraseña":"Reset Password",
		"Ingrese una contraseña":"enter a password",
		"Las contraseñas tienen que ser iguales":"Passwords must be equal",
		"demasiado corto":"too short",
		"bueno":"good",
		"fuerte":"strong",
		"Tipo de Cambio":"Exchange Rates",
		"Listado Tipo de Cambio Moneda":"Currency Exchange Rates List",
		"Valor USD.":"Value USD.",
		"Valor Bs.":"Value Bs",
		"Fecha Registro":"Registration Date",
		"Vigente":"in force",
		"Nuevo Registro Tipo de Cambio":"New Record Exchange",
		"ingrese valor Bs.":"enter value Bs",
		"Editar Tipo de Cambio":"Edit Exchange Rate",
		"Administrar parametros del Producto":"Administer Product parameters",
		"Administrar Producto Crediticio":"Administer Product Credit",
		"Administrar preguntas":"Administer Questions",
		"Administrar producto extra":"Administer extra output",
		"Administrar contenido":"Administer Content",
		"Administrar Certificado Médico":"Administer Medical Certificate",
		"Administrar Ocupación":"Administer Occupation",
		"Administrar Estados":"Administer States",
		"Administrar parametros del Producto Desgravamen":"Administer Product parameters Disencumbrance",
		"Caducidad Cotización (días)":"Quote Expiration (days)",
		"Monto Max Cotización (usd)":"Max Amount Quotation (usd)",
		"Monto Max Cotización (bs)":"Max Amount Quotation (bs)",
		"Monto Max Emisión (usd)":"Max Amount Emission (usd)",
		"Monto Max Emisión (bs)":"Max Amount Emission (bs)",
		"Edad Mínima":"Minimum Age",
		"Edad Máxima":"Maximum Age",
		"Nro Titulares":"Number Headlines",
		"Implante":"implant",
		"Certificado Provisional":"Provisional certificate",
		"Editar Datos Desgravamen":"Disencumbrance Edit Data",
		"Monto Máximo Cotización (Bs)":"Maximum Quotation Amount (Bs)",
		"Monto Máximo Cotización (USD)":"Maximum Quotation Amount (USD)",
		"Monto Máximo Emisión (Bs)":"Maximum Emission Amount (Bs)",
		"Monto Máximo Emisión (USD)":"Maximum Emission Amount (USD)",
		"Numero de Titulares":"Number of Owners",
		"seleccione edad minima":"select minimum age",
		"seleccione edad maxima":"select maximum age",
		"ingrese solo numeros":"Enter just numbers",
		"ingrese numero de titulares":"enter number of holders",
		"Lista Registros":"List Records",
		"Tipo registro":"registration Type",
		"Compañía de Seguro":"Insurance Company",
		"Agregar nuevo registro":"Add new record",
		"Tipo de registro":"Record Type",
		"seleccione tipo registro":"select record type",
		"Listado de Productos":"List of Products",
		"Agregar Productos":"Add products",
		"ingrese producto":"enter product",
		"ingrese solo caracteres":"enter only characters",
		"Editar Productos":"edit products",
		"Editar Tasas":"Edit Rates",
		"Tasa Compañía":"Fee Company",
		"Tasa Banco":"Bank fee",
		"Tasa Final":"Final fee",
		"Agregar nuevas tasas":"Add new rates",
		"No existe registros alguno, para ingresar nuevas tasas añada un nuevo producto":"There is no record, to enter new rates add a new product",
		"Administrar preguntas Desgravamen":"Administer Questions Disencumbrance",
		"Listado de Preguntas":"List of Questions",
		"Preguntas":"Questions",
		"Respuesta esperada":"expected response",
		"Crear Pregunta":"create Question",
		"Pregunta":"Question",
		"ingrese la pregunta":"enter the question",
		"seleccione respuesta":"select answer",
		"Editar Pregunta":"edit Ask",
		"Contenido Desgravamen":"content Disencumbrance",
		"Actualizar Contenido Desgravamen":"Disencumbrance Content Update",
		"El tamaño máximo del archivo es de 1Mb. Se recomienda que la imagen tenga un alto de 100px., el formato del archivo a subir debe ser [jpg]":"The maximum file size is 1MB. It is recommended that the image has a height of 100px., The format of the file to upload should be [jpg]",
		"Archivo":"File",
		"Listado Producto Extra":"Product List Extra",
		"Rango (Bs)":"Range (Bs)",
		"Rango (USD)":"Range (USD)",
		"Hospitalario (USD)":"Hospitaller (USD)",
		"Vida (USD)":"Life (USD)",
		"Cesantía (USD)":"Severance Pay (USD)",
		"Total Prima (USD)":"Total premium (USD)",
		"Crear Poducto Extra":"Create Extra On product",
		"Rango Mínimo":"Minimum Range",
		"Rango Máximo":"Maximum Range",
		"Prima":"Premium",
		"Ingrese el rango mínimo":"Enter the minimum range",
		"Editar Poducto Extra":"On product Edit Extra",
		"Editar Certificado Médico":"Edit Medical Certificate",
		"Listado Certificados Médicos":"Listed Medical Certificates",
		"Tipo Certificado":"Certificate Type",
		"Titulo":"Title",
		"Crear Nuevo Certificado Médico":"Add New Medical Certificate",
		"seleccione tipo certificado":"select type certificate",
		"Ingrese el titulo":"Enter the title",
		"Listado Cuestionario":"list Questionnaire",
		"Titulo Cuestionario":"Title Questionnaire",
		"No existe ningun dato, ingrese nuevos registros":"There is not any data, enter new records",
		"Crear nuevo Cuestionario":"Create new Questionnaire",
		"ingrese titulo del cuestionario":"enter title of the questionnaire",
		"Listado Preguntas":"list Questions",
		"Tipo":"Type",
		"Crear nueva Pregunta":"Create new Question",
		"Titulo Pregunta":"Question Title",
		"Tipo pregunta":"question Type",
		"seleccione tipo pregunta":"select question type",
		"Se agrego correctamente el registro":"Registration is successfully added",
		"Listado de cuestionarios agregados":"Listing added questionnaires",
		"Agregar cuestionario a certificado":"Add a certificate questionnaire",
		"Tipo de certificado":"Certificate Type",
		"seleccione tipo de cuestionario":"select type of questionnaire",
		"Listado de preguntas agregadas":"Listing added questions",
		"Agregar pregunta a cuestionario":"Add Question questionnaire",
		"seleccione pregunta":"select question",
		"Listado de Registros Ocupación":"List of Occupation Records",
		"Titulo Ocupación":"Job Title",
		"Nuevo Registro Ocupación":"New Record Occupation",
		"Codigo Ocupación":"Occupation Code",
		"Ingrese ocupacion":"Enter occupancy",
		"Editar Registro Ocupación":"Edit Registry Occupation",
		"Listado de Registros Estados":"List of Records United",
		"Nuevo Registro Estado":"New State Record",
		"Titulo Estado":"State Title",
		"Seleccione el estado":"Select the state",
		"Administrar tasas":"Administer rates",
		"Administrar tipo vehículo":"Administer vehicle type",
		"Administrar marca/modelo":"Administer brand / model",
		"Administrar Ocupacion":"Administer Occupation",
		"Administrar Forma de Pago":"Administer Payment Form",
		"No existe ningun registro, probablemente se debe a":"There is no record, probably due to",
		"La Entidad Financiera no tiene asignado el producto Automotores":"The Financial Institution has not assigned the Automotive Product",
		"La Entidad Financiera no esta activado":"The Financial Institution is not activated",
		"La Entidad Financiera no esta creada":"The Financial Institution is not created",
		"Administrar parametros del Producto Automotores":"administer Automotive Product parameters",
		"Monto Facultativo":"Facultative amount",
		"Nro Autos":"Number Autos",
		"Facturación":"Billing",
		"Antigüedad del vehiculo":"Age of vehicle",
		"Editar Datos Automotores":"Edit Data Automotive",
		"Numero de Autos":"Number of Cars",
		"No existe ningun registro, razones alguna":"here is no record, some reasons",
		"Agregar nueva tasa":"Add new rate",
		"Tasa":"rates",
		"Tasa Incremento":"rates Increase",
		"ingrese la tasa":"enter the rate",
		"ingrese incremento":"enter increase",
		"Listado tipo de vehiculos":"List types of vehicles",
		"Tipo Vehículo":"Vehicle Type",
		"Agregar Tipo de Vehiculo":"Add Vehicle Type",
		"Tipo de Vehículo":"Type of Vehicle",
		"ingrese el tipo de vehiculo":"Enter the type of vehicle",
		"ingrese solo carcateres":"enter only default character",
		"Editar Tipo de Vehiculo":"Edit Type of Vehicle",
		"Listado marcas auto":"List auto brands",
		"Marca de Auto":"Auto Brand",
		"Agregar Marca de Auto":"Add Auto Brand",
		"ingrese marca de auto":"enter car brand",
		"Editar Marca de Auto":"Edit Auto Brand",
		"Listado modelos auto":"List car models",
		"Marca":"Brand",
		"Modelo de Auto":"Auto Model",
		"Agregar Modelo de Auto":"Add Model Auto",
		"ingrese modelo de auto":"enter car model",
		"Editar Modelo de Auto":"Model Auto Edit",
		"El modelo de auto ya existe, ingrese otro modelo":"The car model already exists, enter another model",
		"Contenido Automotores":"Automotive Content",
		"Actualizar Contenido Automotores":"Automotive Content Update",
		"Listado de Registros Forma de Pago":"List of Records Form of Payment",
		"Nuevo Registro Forma de Pago":"New Registration Form of Payment",
		"Forma de Pago":"Method of payment",
		"Seleccione forma de pago":"Select payment",
		"Administrar parámetros del Producto Todo Riesgo Domiciliario":"Manage Settings Household Product All Risk",
		"Nro Registros":"Record Number",
		"Editar datos Todo Riesgo Domiciliario":"Edit Data All Risk Household",
		"Numero de Registros":"Number of Records",
		"ingrese caducidad cotizacion":"enter expiration quote",
		"ingrese monto maximo usd":"Enter maximum amount usd",
		"ingrese monto maximo emision usd":"enter emission maximum amount usd",
		"La Compañía de Seguros no esta activada":"The Insurance Company is not activated",
		"La Compañía asignada a la Entidad Financiera no esta activada":"The Company assigned to the Financial Institution is not activated",
		"El producto no existe en la Compañía asignada a la Entidad Financiera":"The product is available in the Company assigned to the Financial Institution",
		"Tasa Año":"rate Year",
		"Tasa Restante":"rate Remaining",
		"Tasa Estandar":"Standard rate",
		"campo obligatorio":"required field",
		"ingrese solo numeros enteros o decimales":"only enter integer or decimal numbers",
		"Se registro correctamente los datos del formulario":"Form data is properly record",
		"Contenido Todo Riesgo Domiciliario":"Content All Domiciliary Risk",
		"Actualizar Contenido Todo Riesgo Domiciliario":"Update Content All Domiciliary Risk",
		"La Entidad Financiera no tiene asignado el producto Todo Riesgo Domiciliario":"The Financial Institution has not assigned Domiciliary Product All Risk",
		"Editar":"Edit",
		"Eliminar":"Remove",
		"Añadir Ocupacion":"Add Occupation",
		"Añadir Estado":"Add State",
		"Añadir Forma Pago":"Add Form Payments",
		"Todo Riesgo Equipo Movil":"All Risk Mobile Equipment",
		"Administrar parametros del Producto Ramos Técnicos":"Managing Technical Product parameters Ramos",
		"Editar Parametros del Producto Ramos Técnicos":"Product Technical Parameters Edit Ramos",
		"La Entidad Financiera no tiene asignado el producto Todo Riesgo Equipo Movil":"The Financial Institution is not assigned a product All Risk Mobile Equipment",
		"Hubo un error al ingresar los datos, consulte con su administrador":"Hubo un error al ingresar los datos, consulte con su administrador",
		"Añadir nuevas tasas":"Add new rates",
		"no puede ingresar mas de tres tasas":"You can not enter more than three rates",
		"campo requerido":"field required",
		"Administrar tarjeta":"administer card",
		"Administrar marca":"administer brand",
		"Administrar primas":"Administer premiums",
		"Lista Tipo de Tarjeta":"Card Type List",
		"Tipo de Tarjeta":"Card Type",
		"Agregar Tipo de Tarjeta":"Add Card Type",
		"seleccione tipo de tarjeta":"select type of card",
		"el tipo de tarjeta ya existe, seleccione otro":"card type already exists, select another",
		"Se creo correctamente el registro":"It was created correctly record",
		"Hubo un error al crear el registro, consulte con su administrador":"There was an error creating the registry, see your administrator",
		"Administrar marca tarjeta":"administer brand card",
		"Administrar Primas Tarjeta":"administer Premium Card",
		"No existe registros alguno, razones alguna":"There is no record, some reasons",
		"Verifique que el producto exista en la Compañía asignada a la Entidad Financiera":"Verify that the product exists in the Company assigned to the Financial Institution",
		"Actualizar Contenido Tarjetahabiente":"Update Cardholder Content",
		"Administrar parametros del Producto Tarjetahabiente":"Administer Product parameters Cardholder",
		"Editar Datos Tarjetahabiente":"Edit Cardholder Data",
		"Listado Marca de Tarjetas":"Brand Card List",
		"Marca de la Tarjeta":"Brand Card",
		"Añadir marca tarjeta":"Add Brand Card",
		"Agregar Marca de la Tarjeta":"Add Brand Card",
		"seleccione la marca de tarjeta":"select the brand of card",
		"Inactivo":"inactive",
		"Administrar primas tarjeta":"administer Premium Card",
		"Listado Primas Tarjeta":"Premium Card List",
		"ingrese la prima":"enter the premium",
		"Administrar Correos":"administer Mail office",
		"listado de correos":"mailing list",
		"Crear nuevo correo electrónico":"Create new email",
		"seleccione producto":"select product",
		"ingrese nombre":"enter name",
		"Editar correo electrónico":"Edit email",
		"Departamentos":"Departments",
		"Sucursales":"Locations",
		"Listar Departamentos":"Departments list",
		"Listado Departamentos/Sucursales":"List Departments/Locations",
		"Tipo CI":"Type CI",
		"Tipo Regional":"Regional Type",
		"Tipo Departamento":"Type Department",
		"Acción":"action",
		"Añadir Nuevo Registro":"Add New Record",
		"Añadir Nuevo Departamento/Sucursal":"Add New Department/Branch",
		"Departamento/Sucursal":"Department/Branch",
		"Regional":"regional",
		"Departamento":"departament",
		"ingrese la agencia":"enter the agency",
		"debe seleccionar al menos un tipo":"must select at least one type",
		"ingrese solo alfanumericos":"enter only alphanumeric",
		"Editar Departamento/Sucursal":"Edit Department/Branch",
		"Listar Agencias":"Agencies list",
		"Añadir nueva agencia":"Add new agency",
		"listado de agencias":"List of agencies",
		"Emisión":"emission",
		"seleccione regional":"select regional",
		"Listar formularios":"list forms",
		"Agregar formulario":"Add Form",
		"Listado Formularios":"list Forms",
		"Nuevo Archivo":"new File",
		"El tamaño máximo del archivo es de 2Mb, el formato del archivo a subir debe ser [PDF]":"The maximum file size is 2Mb, the file format should be up [PDF]",
		"Debe seleccionar un archivo.":"You must select a file",
		"El archivo no pudo ser copiado al servidor, el archivo no tiene un formato permitido. image/gif":"The file could not be copied to the server, the file is not a valid format. image/gif",
		"Editar Archivo":"edit File",
		"No existe una cabecera creada para la nueva Entidad Financiera, consulte con su administrador":"There is no header created for the new financial institution, consult your administrator",
		"Verificar que la Entindad Financiera este activa, consulte con su administrador":"Check the Financial Entindad is active, see your administrator",
		"La Entidad Financiera no tiene asignado un producto":"The Financial Institution is not assigned a product",
		"La Entidad Financiera no tiene asignado el producto Desgravamen":"The Financial Institution has not allocated the Debtor product",
		"La Entidad Financiera no tiene asignado el producto Tarjetahabiente":"The Financial Institution is not assigned product Cardmember",
		"Agregar Registro":"Add Record",
		"Activar":"active",
		"Desactivar":"deactivate",
		"Esta seguro de activar la Entidad Financiera":"Sure to activate the Financial Institution",
		"Agregar Cia. Seguros":"Add Insurance Company",
		"Editar pólizas":"edit policies",
		"Añadir nueva póliza":"Add new policy",
		"Editar Póliza":"Edit policy",
		"Nro Poliza":"Policy Number",
		"Añadir Cia. a Entindad":"Add Company to Entity",
		"Agregar nuevo usuario":"Add new user",
		"dar baja":"give low",
		"dar alta":"give high",
		"Añadir Registro":"Add Register",
		"Agregar lista productos":"Add products list",
		"Editar Tasas Producto":"Edit Fees Product",
		"Añadir Producto":"Add Product",
		"Añadir nueva pregunta":"Add new question",
		"Certificados Medicos":"Medical certificates",
		"Crear Certificado":"create Certificate",
		"Crear Cuestionario":"create Questionnaire",
		"Crear Preguntas":"create Questions",
		"Agregar Cuestionario":"Add Questionnaire",
		"Agregar preguntas":"Add questions",
		"Se registro correctamente el dato":"Data was correctly record",
		"Hubo un error al ingresar el dato, consulte con su administrador":"There was an error while entering your data, contact your administrator",
		"Se edito correctamente los datos":"Data were edited correctly",
		"Añadir tipo vehiculo":"Add vehicle type",
		"Añadir marca auto":"Add car brand",
		"Agregar Modelo Auto":"Add Model Car"
		
		
	},
	"regex": [
	    [/Inicio/, "Home"],
		[/Si/, "Yes"],
		[/No/, "No"],
		[/Activo/, "Active"],
		[/CUESTIONARIO/,"QUESTIONNAIRE"],
		[/Cuestionario/, "Questionnaire"],
		[/Nro/, "Number"],
		[/^Something at start of text/, ""],
		[/This will be case insensitive/i, ""]
	]
};